project:
  type: website
  output-dir: docs

website:
  title: "r-software-lifetime"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: r-news.qmd
        text: r-news
      - href: about.qmd
        text: about
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/CU-DBMI/r-software-lifetime
          - text: Report a Bug
            href:  https://github.com/CU-DBMI/r-software-lifetime/issues/new
  site-url: "https://cu-dbmi.github.io/r-software-lifetime/"
  repo-url: "https://github.com/CU-DBMI/r-software-lifetime"
  repo-branch: main
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
